language: node_js
node_js:
  - "6"
before_install:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - npm install -g instagram-profilecrawl
script:
  - instagram-profilecrawl nacim --chrome